export interface QuizQuestion {
  question: string
  options: string[]
  correctIndex: number
  category: string
  type: 'multiple' | 'truefalse'
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // === Englisch (20) ===
  { question: 'Was bedeutet "dog"?', options: ['Katze', 'Hund', 'Vogel', 'Fisch'], correctIndex: 1, category: 'Englisch', type: 'multiple' },
  { question: '"Thank you" heisst auf Deutsch...', options: ['Bitte', 'Entschuldigung', 'Danke', 'Hallo'], correctIndex: 2, category: 'Englisch', type: 'multiple' },
  { question: '"Blue" ist eine Farbe.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Englisch', type: 'truefalse' },
  { question: 'Was bedeutet "grandmother"?', options: ['Tante', 'Grossmutter', 'Schwester', 'Mutter'], correctIndex: 1, category: 'Englisch', type: 'multiple' },
  { question: '"Apple" bedeutet Birne.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Englisch', type: 'truefalse' },
  { question: 'Was bedeutet "pencil"?', options: ['Lineal', 'Bleistift', 'Buch', 'Schere'], correctIndex: 1, category: 'Englisch', type: 'multiple' },
  { question: '"Elephant" ist ein kleines Tier.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Englisch', type: 'truefalse' },
  { question: 'Was bedeutet "to swim"?', options: ['laufen', 'schwimmen', 'fliegen', 'springen'], correctIndex: 1, category: 'Englisch', type: 'multiple' },
  { question: '"Good morning" sagt man abends.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Englisch', type: 'truefalse' },
  { question: 'Was bedeutet "shoulder"?', options: ['Knie', 'Schulter', 'Ellbogen', 'Handgelenk'], correctIndex: 1, category: 'Englisch', type: 'multiple' },
  { question: '"Rain" bedeutet Sonne.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Englisch', type: 'truefalse' },
  { question: 'Was bedeutet "jacket"?', options: ['Hose', 'Jacke', 'Hemd', 'Schal'], correctIndex: 1, category: 'Englisch', type: 'multiple' },
  { question: '"Yesterday" bedeutet morgen.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Englisch', type: 'truefalse' },
  { question: 'Was bedeutet "to cook"?', options: ['kochen', 'backen', 'essen', 'trinken'], correctIndex: 0, category: 'Englisch', type: 'multiple' },
  { question: '"Three" ist die Zahl 3.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Englisch', type: 'truefalse' },
  { question: 'Was bedeutet "butterfly"?', options: ['Biene', 'Schmetterling', 'Kaefer', 'Spinne'], correctIndex: 1, category: 'Englisch', type: 'multiple' },
  { question: '"Cheese" bedeutet Kaese.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Englisch', type: 'truefalse' },
  { question: 'She ___ a student. (richtige Form)', options: ['am', 'is', 'are', 'be'], correctIndex: 1, category: 'Englisch', type: 'multiple' },
  { question: 'I have ___ apple. (Artikel)', options: ['a', 'an', 'the', '--'], correctIndex: 1, category: 'Englisch', type: 'multiple' },
  { question: 'He ___ football. (Simple Present)', options: ['play', 'plays', 'playing', 'played'], correctIndex: 1, category: 'Englisch', type: 'multiple' },

  // === Mathe (25) ===
  { question: 'Was ist 7 x 8?', options: ['54', '56', '58', '63'], correctIndex: 1, category: 'Mathe', type: 'multiple' },
  { question: 'Was ist 25% von 200?', options: ['25', '50', '75', '100'], correctIndex: 1, category: 'Mathe', type: 'multiple' },
  { question: '144 / 12 = 12', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Mathe', type: 'truefalse' },
  { question: 'Was ist 3/4 + 1/4?', options: ['1/2', '1', '3/4', '2/4'], correctIndex: 1, category: 'Mathe', type: 'multiple' },
  { question: 'Die Flaeche eines Quadrats mit Seite 5 cm ist 20 cm2.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Mathe', type: 'truefalse' },
  { question: 'Was ist 9 x 9?', options: ['72', '81', '90', '63'], correctIndex: 1, category: 'Mathe', type: 'multiple' },
  { question: 'Was ist 50% von 80?', options: ['20', '30', '40', '60'], correctIndex: 2, category: 'Mathe', type: 'multiple' },
  { question: '15 + 27 = 42', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Mathe', type: 'truefalse' },
  { question: 'Was ist 1000 - 350?', options: ['550', '600', '650', '700'], correctIndex: 2, category: 'Mathe', type: 'multiple' },
  { question: '6 x 7 = 42', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Mathe', type: 'truefalse' },
  { question: 'Was ist der Umfang eines Quadrats mit Seite 8 cm?', options: ['24 cm', '32 cm', '64 cm', '16 cm'], correctIndex: 1, category: 'Mathe', type: 'multiple' },
  { question: 'Was ist (-3) + (-5)?', options: ['-8', '-2', '2', '8'], correctIndex: 0, category: 'Mathe', type: 'multiple' },
  { question: '1/2 = 0,5', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Mathe', type: 'truefalse' },
  { question: 'Was ist 12 x 12?', options: ['124', '132', '144', '156'], correctIndex: 2, category: 'Mathe', type: 'multiple' },
  { question: 'Was ist 10% von 500?', options: ['5', '50', '100', '500'], correctIndex: 1, category: 'Mathe', type: 'multiple' },
  { question: 'Was kommt bei 3 + 4 x 2 raus?', options: ['11', '14', '10', '12'], correctIndex: 0, category: 'Mathe', type: 'multiple' },
  { question: '0,3 + 0,7 = 1,0', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Mathe', type: 'truefalse' },
  { question: 'Was ist 256 / 4?', options: ['54', '62', '64', '66'], correctIndex: 2, category: 'Mathe', type: 'multiple' },
  { question: 'Wie viele Minuten hat eine Stunde?', options: ['30', '45', '60', '90'], correctIndex: 2, category: 'Mathe', type: 'multiple' },
  { question: '1 km = 100 m', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Mathe', type: 'truefalse' },
  { question: 'Was ist 3/5 als Prozent?', options: ['30%', '50%', '60%', '75%'], correctIndex: 2, category: 'Mathe', type: 'multiple' },
  { question: '(-2) x (-3) = 6', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Mathe', type: 'truefalse' },
  { question: 'Was ist 2 hoch 3?', options: ['6', '8', '9', '12'], correctIndex: 1, category: 'Mathe', type: 'multiple' },
  { question: 'Wie viele Sekunden hat eine Minute?', options: ['30', '60', '90', '100'], correctIndex: 1, category: 'Mathe', type: 'multiple' },
  { question: 'Die Haelfte von 1/2 ist 1/4.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Mathe', type: 'truefalse' },

  // === Hockey (15) ===
  { question: 'Wie viele Spieler hat eine Hockey-Mannschaft auf dem Feld?', options: ['9', '10', '11', '12'], correctIndex: 2, category: 'Hockey', type: 'multiple' },
  { question: 'Der Schiedsrichter zeigt eine gruene Karte. Was bedeutet das?', options: ['Tor!', 'Verwarnung', 'Platzverweis', 'Freistoss'], correctIndex: 1, category: 'Hockey', type: 'multiple' },
  { question: 'Im Hockey darf man den Ball mit dem Fuss spielen.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Hockey', type: 'truefalse' },
  { question: 'Wie lang ist eine Halbzeit?', options: ['25 Min.', '30 Min.', '35 Min.', '45 Min.'], correctIndex: 2, category: 'Hockey', type: 'multiple' },
  { question: 'Man darf mit der runden Seite des Schlaegers spielen.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Hockey', type: 'truefalse' },
  { question: 'Was ist eine Kurzecke?', options: ['Ein Eckstoss', 'Eine Standardsituation bei Foul im Kreis', 'Ein Freistoss', 'Ein Einwurf'], correctIndex: 1, category: 'Hockey', type: 'multiple' },
  { question: 'Seit wann ist Hockey olympisch (Maenner)?', options: ['1896', '1908', '1924', '1936'], correctIndex: 1, category: 'Hockey', type: 'multiple' },
  { question: 'Das Spielfeld ist 55 m breit.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Hockey', type: 'truefalse' },
  { question: 'Was bedeutet eine gelbe Karte?', options: ['2 Min. Strafe', '5-10 Min. Zeitstrafe', 'Platzverweis', 'Verwarnung'], correctIndex: 1, category: 'Hockey', type: 'multiple' },
  { question: 'Wie viele Schiedsrichter leiten ein Spiel?', options: ['1', '2', '3', '4'], correctIndex: 1, category: 'Hockey', type: 'multiple' },
  { question: 'Was ist "Indischer Dribbling"?', options: ['Ball schnell hin und her fuehren', 'Rueckwaerts laufen', 'Ball hochwerfen', 'Mit beiden Haenden spielen'], correctIndex: 0, category: 'Hockey', type: 'multiple' },
  { question: 'Deutschland ist eine starke Hockey-Nation.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Hockey', type: 'truefalse' },
  { question: 'Was ist ein Push?', options: ['Ein Schlag', 'Eine Schiebebewegung', 'Ein Wurf', 'Ein Kopfball'], correctIndex: 1, category: 'Hockey', type: 'multiple' },
  { question: 'Tore zaehlen auch aus dem Mittelfeld.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Hockey', type: 'truefalse' },
  { question: 'Mundschutz ist im Hockey Pflicht.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Hockey', type: 'truefalse' },

  // === KI (15) ===
  { question: 'Was ist KI?', options: ['Ein Computerspiel', 'Kuenstliche Intelligenz', 'Eine Programmiersprache', 'Ein Roboter'], correctIndex: 1, category: 'KI', type: 'multiple' },
  { question: 'KI kann aus Daten lernen.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'KI', type: 'truefalse' },
  { question: 'Was macht ein Sprachmodell?', options: ['Bilder malen', 'Text verstehen und erzeugen', 'Musik spielen', 'Videos schneiden'], correctIndex: 1, category: 'KI', type: 'multiple' },
  { question: 'KI kann Bilder erkennen.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'KI', type: 'truefalse' },
  { question: 'Was braucht eine KI zum Lernen?', options: ['Strom', 'Daten', 'Internet', 'Kamera'], correctIndex: 1, category: 'KI', type: 'multiple' },
  { question: 'ChatGPT ist eine KI.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'KI', type: 'truefalse' },
  { question: 'Was ist Machine Learning?', options: ['Maschinen reparieren', 'Computer lernen aus Daten', 'Roboter bauen', 'Apps programmieren'], correctIndex: 1, category: 'KI', type: 'multiple' },
  { question: 'KI kann Schach spielen.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'KI', type: 'truefalse' },
  { question: 'Was ist ein Chatbot?', options: ['Ein Roboter', 'Ein Programm das chattet', 'Eine Suchmaschine', 'Ein Spiel'], correctIndex: 1, category: 'KI', type: 'multiple' },
  { question: 'KI hat eigene Gefuehle.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'KI', type: 'truefalse' },
  { question: 'Was ist ein Algorithmus?', options: ['Ein Computer', 'Eine Schritt-fuer-Schritt-Anleitung', 'Ein Roboter', 'Ein Programm'], correctIndex: 1, category: 'KI', type: 'multiple' },
  { question: 'KI wird z.B. in Sprachassistenten verwendet.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'KI', type: 'truefalse' },
  { question: 'Was ist Training bei KI?', options: ['Sport', 'Die KI lernt aus Beispielen', 'Updates installieren', 'Hardware einbauen'], correctIndex: 1, category: 'KI', type: 'multiple' },
  { question: 'KI ersetzt alle Menschen.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'KI', type: 'truefalse' },
  { question: 'Wofuer steht "GPT"?', options: ['General Power Tool', 'Generative Pre-trained Transformer', 'Global Processing Tech', 'Game Player Tool'], correctIndex: 1, category: 'KI', type: 'multiple' },

  // === Allgemeinwissen (25) ===
  { question: 'Wie viele Kontinente gibt es?', options: ['5', '6', '7', '8'], correctIndex: 2, category: 'Allgemein', type: 'multiple' },
  { question: 'Die Erde dreht sich um die Sonne.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Allgemein', type: 'truefalse' },
  { question: 'Welches ist das groesste Tier der Welt?', options: ['Elefant', 'Blauwal', 'Giraffe', 'Dinosaurier'], correctIndex: 1, category: 'Allgemein', type: 'multiple' },
  { question: 'Wasser kocht bei 100 Grad C.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Allgemein', type: 'truefalse' },
  { question: 'Was ist die Hauptstadt von Deutschland?', options: ['Muenchen', 'Hamburg', 'Berlin', 'Koeln'], correctIndex: 2, category: 'Allgemein', type: 'multiple' },
  { question: 'Die Sonne ist ein Stern.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Allgemein', type: 'truefalse' },
  { question: 'Wie viele Planeten hat unser Sonnensystem?', options: ['7', '8', '9', '10'], correctIndex: 1, category: 'Allgemein', type: 'multiple' },
  { question: 'Ein Dreieck hat 4 Ecken.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Allgemein', type: 'truefalse' },
  { question: 'Welcher Planet ist der groesste?', options: ['Erde', 'Mars', 'Jupiter', 'Saturn'], correctIndex: 2, category: 'Allgemein', type: 'multiple' },
  { question: 'Der Mond leuchtet selbst.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Allgemein', type: 'truefalse' },
  { question: 'Wie heisst der hoechste Berg der Welt?', options: ['Mont Blanc', 'K2', 'Mount Everest', 'Kilimandscharo'], correctIndex: 2, category: 'Allgemein', type: 'multiple' },
  { question: 'In welchem Land steht die Freiheitsstatue?', options: ['England', 'Frankreich', 'USA', 'Kanada'], correctIndex: 2, category: 'Allgemein', type: 'multiple' },
  { question: 'Delfine sind Fische.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Allgemein', type: 'truefalse' },
  { question: 'Wie viele Bundeslaender hat Deutschland?', options: ['12', '14', '16', '18'], correctIndex: 2, category: 'Allgemein', type: 'multiple' },
  { question: 'Berlin liegt an der Spree.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Allgemein', type: 'truefalse' },
  { question: 'Was ist H2O?', options: ['Sauerstoff', 'Wasser', 'Wasserstoff', 'Kohlendioxid'], correctIndex: 1, category: 'Allgemein', type: 'multiple' },
  { question: 'Spinnen haben 6 Beine.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Allgemein', type: 'truefalse' },
  { question: 'Was ist das groesste Land der Welt?', options: ['China', 'USA', 'Kanada', 'Russland'], correctIndex: 3, category: 'Allgemein', type: 'multiple' },
  { question: 'Der Nil ist der laengste Fluss der Welt.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Allgemein', type: 'truefalse' },
  { question: 'In welcher Stadt steht der Eiffelturm?', options: ['London', 'Paris', 'Rom', 'Madrid'], correctIndex: 1, category: 'Allgemein', type: 'multiple' },
  { question: 'Ein Oktopus hat 10 Arme.', options: ['Wahr', 'Falsch'], correctIndex: 1, category: 'Allgemein', type: 'truefalse' },
  { question: 'Was ist Photosynthese?', options: ['Lichtbild machen', 'Pflanzen erzeugen Sauerstoff', 'Strom erzeugen', 'Wasser erhitzen'], correctIndex: 1, category: 'Allgemein', type: 'multiple' },
  { question: 'Welches Gas atmen wir ein?', options: ['Stickstoff', 'Sauerstoff', 'CO2', 'Helium'], correctIndex: 1, category: 'Allgemein', type: 'multiple' },
  { question: 'Der Mars wird auch "roter Planet" genannt.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Allgemein', type: 'truefalse' },
  { question: 'Wie viele Tage hat ein Schaltjahr?', options: ['364', '365', '366', '367'], correctIndex: 2, category: 'Allgemein', type: 'multiple' },

  // === Natur & Wissenschaft (5) ===
  { question: 'Was passiert mit Wasser bei 0 Grad?', options: ['Es verdampft', 'Es gefriert', 'Es bleibt fluessig', 'Es verschwindet'], correctIndex: 1, category: 'Natur', type: 'multiple' },
  { question: 'Regenbogen haben 7 Farben.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Natur', type: 'truefalse' },
  { question: 'Was erzeugen Solarzellen?', options: ['Wasser', 'Wind', 'Strom', 'Waerme'], correctIndex: 2, category: 'Natur', type: 'multiple' },
  { question: 'Baeume produzieren Sauerstoff.', options: ['Wahr', 'Falsch'], correctIndex: 0, category: 'Natur', type: 'truefalse' },
  { question: 'Welches Organ pumpt Blut durch den Koerper?', options: ['Lunge', 'Gehirn', 'Herz', 'Magen'], correctIndex: 2, category: 'Natur', type: 'multiple' },
]
